// Enter the API keys for each API here
WATSONURL = "https://gateway.watsonplatform.net/tone-analyzer/api";
WATSONKEY = '';
WATSONUSER = '';
WATSONPW = '';
TWITCONSUMERKEY = '';
TWITCONSUMERSECRET = '';
TWITACCESSTOKEN = '';
TWITACCESSTOKENSECRET = '';
module.exports = {
  WATSONURL,
  WATSONKEY,
  WATSONUSER,
  WATSONPW,
  TWITCONSUMERKEY,
  TWITCONSUMERSECRET,
  TWITACCESSTOKEN,
  TWITACCESSTOKENSECRET
};
